on:
  push:
  pull_request:
    branches:
      - devel

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (Bioc ${{ matrix.config.bioc-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-2022, bioc-version: 'devel'}
        - { os: macOS-latest, bioc-version: 'devel'}
        - { os: ubuntu-22.04, bioc-version: 'devel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install system libraries
        if: ${{ runner.os == 'Linux'  }}
        run: |
          sudo apt-get update && sudo apt-get install libcurl4-openssl-dev
          
      - name: Install Mac system libraries
        if: ${{ matrix.config.os == 'macOS-latest' }}
        run: |
          brew install openssl
    
      - name: Configure git
        run: | 
          git config --global core.autocrlf false
          git config --global user.email "ghau@example.com"
          git config --global user.name "GitHub Actions User"
        
      - uses: actions/checkout@v3

      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: https://ftp.gwdg.de/pub/misc/bioconductor
          
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck
        
      - name: Bioc - Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@v1
        
      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          error-on: 'never'
          arguments: '--no-check-bioc-help' 
          
      - name: Test coverage
        if: ${{ matrix.config.os == 'ubuntu-22.04' }}
        run: |
          install.packages('covr')
          covr::codecov()
        shell: Rscript {0}

      ## upload the Rcheck folder if the workflow fails
      - name: Upload output
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ matrix.os }}-bioc-${{ matrix.bioc-version}}
          path: |
            ${{ steps.build-install-check.outputs.check-dir }}
